"""Detection of code the applicant may not own.

A registration covers the applicant's own authorship. Vendored libraries,
generated files and headers naming a different copyright holder all need a
decision - exclude them, or disclaim them in the application - before the
deposit is filed.
"""

from __future__ import annotations

import hashlib
import re

from . import SEVERITY_HIGH, SEVERITY_LOW, SEVERITY_MEDIUM, Finding

HEADER_LINES = 60

# A real notice carries a (c)/copyright symbol or a year. Without that
# requirement the word "copyright" in ordinary prose - or in a variable
# name - produces a flood of false positives.
_COPYRIGHT = re.compile(
    r"(?i)\bcopyright\b\s*(?P<sym>\(c\)|©|&copy;)?\s*"
    r"(?P<years>\d{4}(?:\s*[-,]\s*\d{4})*)?\s*"
    r"(?:by\s+)?(?P<holder>[^\n<]{2,80})?"
)

# A plausible human or organisation name, not a fragment of source code.
_HOLDER_OK = re.compile(r"^[A-Za-z][A-Za-z0-9 .,&'’à-ÿ-]{1,60}$")
_SPDX = re.compile(r"SPDX-License-Identifier:\s*(?P<id>[A-Za-z0-9.\-+ ()]+)")

_LICENSE_PHRASES: tuple[tuple[str, str], ...] = (
    ("apache license", "Apache License"),
    ("mit license", "MIT License"),
    ("bsd license", "BSD License"),
    ("redistribution and use in source and binary forms", "BSD-style licence text"),
    ("gnu general public license", "GNU GPL"),
    ("gnu lesser general public license", "GNU LGPL"),
    ("mozilla public license", "Mozilla Public License"),
    ("permission is hereby granted, free of charge", "MIT-style permission notice"),
)

_GENERATED_PHRASES: tuple[str, ...] = (
    "do not edit",
    "do not modify",
    "@generated",
    "autogenerated",
    "auto-generated",
    "automatically generated",
    "generated by",
    "this file was generated",
    "code generated by",
)

_VENDOR_SEGMENTS = (
    "vendor", "third_party", "thirdparty", "external", "extern", "deps",
    "node_modules", "site-packages", "lib/external",
)

_CORP_SUFFIXES = re.compile(
    r"(?i)\b(inc|inc\.|llc|ltd|ltd\.|limited|gmbh|corp|corporation|co|company|"
    r"foundation|project|team|authors|contributors|and contributors|all rights reserved)\b"
)
_NON_WORD = re.compile(r"[^a-z0-9]+")


def _normalise_holder(name: str) -> str:
    name = name.strip().strip(".,;:-* \t")
    name = _CORP_SUFFIXES.sub(" ", name.lower())
    return _NON_WORD.sub(" ", name).strip()


def _finding_id(rel_path: str, rule: str, detail: str) -> str:
    digest = hashlib.sha256(f"{rel_path}|{rule}|{detail}".encode("utf-8")).hexdigest()
    return f"{rule}-{digest[:12]}"


def _same_owner(holder: str, owner: str) -> bool:
    left, right = _normalise_holder(holder), _normalise_holder(owner)
    if not left or not right:
        return False
    return left == right or left in right or right in left


def scan_text(
    rel_path: str,
    comment_lines: list[str],
    declared_owner: str = "",
) -> list[Finding]:
    """Inspect a file's header comments (and path) for third-party markers.

    `comment_lines` is the file with all non-comment characters blanked out
    (see ``strip.comments_only_lines``), so line numbers stay accurate while
    the scanner never reads a character of actual code.
    """
    findings: list[Finding] = []
    lines = list(comment_lines)
    head = "\n".join(lines[:HEADER_LINES])
    lowered = head.lower()

    lowered_path = rel_path.lower()
    for segment in _VENDOR_SEGMENTS:
        if f"/{segment}/" in f"/{lowered_path}":
            findings.append(
                Finding(
                    id=_finding_id(rel_path, "vendored-path", segment),
                    rel_path=rel_path,
                    line_number=1,
                    rule="vendored-path",
                    detail=f"path contains '{segment}', which usually holds third-party code",
                    severity=SEVERITY_MEDIUM,
                    category="third-party",
                )
            )
            break

    for number, line in enumerate(lines[:HEADER_LINES], start=1):
        match = _COPYRIGHT.search(line)
        if not match:
            continue
        if not (match.group("sym") or match.group("years")):
            continue  # the word alone is not a notice
        holder = (match.group("holder") or "").strip(" .,;:*/-#")
        holder = re.sub(r"(?i)\s*all rights reserved.*$", "", holder).strip(" .,;:*/-")
        if not _HOLDER_OK.match(holder):
            continue
        if declared_owner and _same_owner(holder, declared_owner):
            continue
        findings.append(
            Finding(
                id=_finding_id(rel_path, "foreign-copyright", holder),
                rel_path=rel_path,
                line_number=number,
                rule="foreign-copyright",
                detail=(
                    f"header names '{holder}'"
                    + (f", not '{declared_owner}'" if declared_owner else "")
                ),
                severity=SEVERITY_HIGH if declared_owner else SEVERITY_MEDIUM,
                excerpt=line.strip()[:120],
                category="third-party",
            )
        )
        break

    spdx = _SPDX.search(head)
    if spdx:
        identifier = spdx.group("id").strip()
        findings.append(
            Finding(
                id=_finding_id(rel_path, "spdx-license", identifier),
                rel_path=rel_path,
                line_number=1,
                rule="spdx-license",
                detail=f"declares licence '{identifier}'",
                severity=SEVERITY_LOW,
                category="third-party",
            )
        )
    else:
        for needle, label in _LICENSE_PHRASES:
            if needle in lowered:
                findings.append(
                    Finding(
                        id=_finding_id(rel_path, "license-text", label),
                        rel_path=rel_path,
                        line_number=1,
                        rule="license-text",
                        detail=f"header contains {label} text",
                        severity=SEVERITY_MEDIUM,
                        category="third-party",
                    )
                )
                break

    for needle in _GENERATED_PHRASES:
        if needle in lowered:
            findings.append(
                Finding(
                    id=_finding_id(rel_path, "generated-file", needle),
                    rel_path=rel_path,
                    line_number=1,
                    rule="generated-file",
                    detail=f"header says '{needle}'; generated code is usually not registrable authorship",
                    severity=SEVERITY_MEDIUM,
                    category="third-party",
                )
            )
            break

    return findings
