"""Pre-flight scanners.

Both scanners are judged on false positives as much as on detection: an
alarm that fires on ordinary code trains the operator to ignore it.
"""

from __future__ import annotations

from copyright_deposit.config import TransformOptions
from copyright_deposit.core.pipeline import Pipeline
from copyright_deposit.core.scanning import SEVERITY_HIGH
from copyright_deposit.core.scanning import secrets, thirdparty
from copyright_deposit.core.strip import comments_only_lines, strip_source


def comment_lines(source: str, path: str = "a.py") -> list[str]:
    result = strip_source(source, path, TransformOptions())
    return comments_only_lines(source, result.comment_spans)


# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------


def test_aws_key_is_detected():
    findings = secrets.scan_text("a.py", 'KEY = "AKIAIOSFODNN7EXAMPLE"\n')
    assert any(f.rule == "aws-access-key" and f.severity == SEVERITY_HIGH for f in findings)


def test_private_key_block_is_detected():
    findings = secrets.scan_text("a.pem", "-----BEGIN RSA PRIVATE KEY-----\n")
    assert any(f.rule == "private-key" for f in findings)


def test_credentials_in_a_url_are_detected():
    findings = secrets.scan_text("a.py", 'DSN = "postgres://user:hunter2@db.example.com/x"\n')
    assert any(f.rule == "connection-string" for f in findings)


def test_high_entropy_assignment_is_detected():
    findings = secrets.scan_text("a.py", 'api_key = "f8Kd0zQ2xR7bN4pW1sT6vY9u"\n')
    assert any(f.rule == "hardcoded-credential" for f in findings)


def test_the_secret_itself_is_never_reported_verbatim():
    value = "AKIAIOSFODNN7EXAMPLE"
    findings = secrets.scan_text("a.py", f'KEY = "{value}"\n')
    assert findings
    for finding in findings:
        assert value not in finding.excerpt
        assert "*" in finding.excerpt


def test_placeholders_do_not_raise_an_alarm():
    source = (
        'password = "changeme"\n'
        'api_key = "your-api-key-here"\n'
        'token = "<YOUR_TOKEN>"\n'
        'secret = "${ENV_SECRET}"\n'
    )
    findings = [f for f in secrets.scan_text("a.py", source) if f.severity == SEVERITY_HIGH]
    assert findings == []


def test_ordinary_code_is_not_flagged():
    source = (
        "def authenticate(user, password):\n"
        "    token = generate_token(user)\n"
        "    return verify(token, password)\n"
    )
    assert secrets.scan_text("a.py", source) == []


def test_findings_have_stable_ids():
    source = 'KEY = "AKIAIOSFODNN7EXAMPLE"\n'
    first = secrets.scan_text("a.py", source)
    second = secrets.scan_text("a.py", source)
    assert [f.id for f in first] == [f.id for f in second]


# ---------------------------------------------------------------------------
# Third-party
# ---------------------------------------------------------------------------


def test_foreign_copyright_holder_is_flagged():
    source = "# Copyright (c) 2019 Some Other Company\nx = 1\n"
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Test Owner")
    assert any(f.rule == "foreign-copyright" for f in findings)


def test_the_declared_owner_is_not_flagged():
    source = "# Copyright (c) 2026 Test Owner. All rights reserved.\nx = 1\n"
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Test Owner")
    assert not any(f.rule == "foreign-copyright" for f in findings)


def test_corporate_suffixes_do_not_defeat_owner_matching():
    source = "# Copyright (c) 2026 Acme Inc.\nx = 1\n"
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Acme")
    assert not any(f.rule == "foreign-copyright" for f in findings)


def test_the_word_copyright_in_prose_is_not_a_notice():
    source = '"""Handles copyright registration for the copyright owner."""\nx = 1\n'
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Test Owner")
    assert not any(f.rule == "foreign-copyright" for f in findings)


def test_copyright_inside_code_is_never_seen():
    source = 'MESSAGE = "Copyright (c) 2019 Someone Else"\nx = 1\n'
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Test Owner")
    assert not any(f.rule == "foreign-copyright" for f in findings)


def test_spdx_identifier_is_reported():
    source = "# SPDX-License-Identifier: Apache-2.0\nx = 1\n"
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Test Owner")
    assert any(f.rule == "spdx-license" for f in findings)


def test_generated_file_marker_is_reported():
    source = "# Code generated by protoc. DO NOT EDIT.\nx = 1\n"
    findings = thirdparty.scan_text("a.py", comment_lines(source), "Test Owner")
    assert any(f.rule == "generated-file" for f in findings)


def test_vendored_path_is_reported():
    findings = thirdparty.scan_text("third_party/lib/a.py", [""], "Test Owner")
    assert any(f.rule == "vendored-path" for f in findings)


# ---------------------------------------------------------------------------
# Blocking behaviour
# ---------------------------------------------------------------------------


def test_build_is_blocked_by_an_unresolved_credential(make_tree, settings_for):
    settings = settings_for(make_tree({"a.py": 'KEY = "AKIAIOSFODNN7EXAMPLE"\n'}))
    result = Pipeline().build(settings)
    assert result.blocked_by
    assert not result.outputs


def test_force_overrides_the_block(make_tree, settings_for):
    settings = settings_for(make_tree({"a.py": 'KEY = "AKIAIOSFODNN7EXAMPLE"\n'}))
    result = Pipeline().build(settings, force=True)
    assert result.outputs


def test_acknowledging_a_finding_unblocks_the_build(make_tree, settings_for):
    settings = settings_for(make_tree({"a.py": 'KEY = "AKIAIOSFODNN7EXAMPLE"\n'}))
    pipeline = Pipeline()
    estimate = pipeline.estimate(settings)
    settings.scan.ignored_findings = [f.id for f in estimate.scan.secrets]
    result = pipeline.build(settings)
    assert not result.blocked_by
    assert result.outputs


def test_redacting_a_credential_still_blocks_until_acknowledged(make_tree, settings_for):
    """Blacking it out changes the PDF, not the fact that it is in the source."""
    settings = settings_for(make_tree({"a.py": 'KEY = "AKIAIOSFODNN7EXAMPLE"\n'}))
    settings.redaction.enabled = True
    settings.redaction.manual_lines = ["a.py:1"]
    result = Pipeline().build(settings)
    assert result.blocked_by
